import { tx } from '@/lib/i18n'

/**
 * Denetim kaydındaki teknik adların (EF varlık adı, işlem kodu) kullanıcıya gösterilen Türkçe karşılıkları.
 * Denetim sayfası ve zaman makinesi ortak kullanır; listede olmayan ad olduğu gibi gösterilir.
 */
export const auditActionLabels: Record<string, string> = {
  Created: tx('Oluşturma'),
  Updated: tx('Güncelleme'),
  Deleted: tx('Silme'),
  SensitiveViewed: tx('Hassas veri görüntüleme'),
  PlatformAccess: tx('Platform yöneticisi erişimi'),
  Revealed: tx('Görüntüleme'),
  SelfServiceViewed: tx('Kendi verisini görüntüleme'),
  Exported: tx('Dışa aktarma'),
  Downloaded: tx('İndirme'),
  Anonymized: tx('Anonimleştirme'),
  Closed: tx('Kapatma'),
  Reopened: tx('Yeniden açma'),
  Verified: tx('Doğrulama'),
  IdentityVerified: tx('Kimlik doğrulama'),
  OtpFailed: tx('Hatalı doğrulama kodu'),
  StepUpConfirmed: tx('Ek doğrulama'),
  Approved: tx('Onay'),
  Decided: tx('Karar'),
  Published: tx('Yayımlama'),
  Signed: tx('İmzalama'),
  Received: tx('Başvuru alındı'),
  Replied: tx('Yanıtlama'),
  ReportedToBoard: tx('Kurul bildirimi'),
  SubjectsNotified: tx('İlgili kişileri bilgilendirme'),
  RetentionPlanned: tx('Saklama planı'),
  AutomatedAnalysis: tx('Otomatik analiz'),
  ValuesUpdated: tx('Değer güncelleme'),
  Applied: tx('Uygulama'),
  Added: tx('Ekleme'),
  Removed: tx('Kaldırma'),
  Completed: tx('Tamamlama'),
  Cancelled: tx('İptal'),
  Calibrated: tx('Kalibrasyon'),
  AccountDisabled: tx('Hesap devre dışı'),
  DefenceRequested: tx('Savunma istendi'),
  DefenceSubmitted: tx('Savunma verildi'),
  AssetsVerified: tx('Zimmet doğrulama'),
  AssetOverride: tx('Zimmet istisnası'),
  MarkedLost: tx('Kayıp bildirimi'),
  ExitSurveyCompleted: tx('Çıkış anketi'),
  ModelRetrainRejected: tx('Model yenileme reddi'),
  PeerAccepted: tx('Değerlendirici kabulü'),
}

export const auditEntityLabels: Record<string, string> = {
  Notification: tx('Bildirim'),
  NotificationPreference: tx('Bildirim tercihi'),
  ChatIdentity: tx('Sohbet hesabı eşleşmesi'),
  ChatApp: tx('Sohbet uygulaması'),
  ChatMessage: tx('Sohbet iletisi'),
  ChatOutbox: tx('Sohbet gönderim kuyruğu'),
  WorkflowRequest: tx('Onay talebi'),
  WorkflowDefinition: tx('Onay akışı'),
  ApprovalStep: tx('Onay adımı'),
  Delegation: tx('Vekâlet'),
  LeaveRequest: tx('İzin talebi'),
  LeaveBalance: tx('İzin bakiyesi'),
  PublicHoliday: tx('Resmî tatil'),
  AiUsage: tx('Yapay zekâ kullanımı'),
  AiSettings: tx('Yapay zekâ ayarları'),
  OvertimeRequest: tx('Fazla mesai talebi'),
  OffboardingCase: tx('Ayrılış süreci'),
  ShiftAssignment: tx('Vardiya ataması'),
  ShiftSwapRequest: tx('Vardiya değişim talebi'),
  ShiftOverride: tx('Vardiya istisnası'),
  ShiftPatternDay: tx('Vardiya deseni'),
  Shift: tx('Vardiya'),
  TimeEntry: tx('Puantaj kaydı'),
  TimeClockCredential: tx('Kart/PIN tanımı'),
  TimeClockSite: tx('Giriş noktası'),
  TimeClockPunch: tx('Giriş-çıkış kaydı'),
  PayrollPeriod: tx('Bordro dönemi'),
  PayrollExport: tx('Bordro dışa aktarımı'),
  PayrollAdjustment: tx('Bordro düzeltmesi'),
  Payslip: tx('Ücret pusulası'),
  CompensationRecord: tx('Ücret kaydı'),
  RaiseCycle: tx('Zam dönemi'),
  RaiseProposal: tx('Zam önerisi'),
  SalaryAdvance: tx('Avans'),
  BenefitOption: tx('Yan hak seçeneği'),
  FxRate: tx('Döviz kuru'),
  Application: tx('Başvuru'),
  Candidate: tx('Aday'),
  Offer: tx('Teklif'),
  Interview: tx('Mülakat'),
  JobPosting: tx('İş ilanı'),
  ScorecardTemplate: tx('Değerlendirme formu'),
  TransferAgreement: tx('Yurt dışı aktarım'),
  DataBreach: tx('Veri ihlali'),
  DataRequest: tx('İlgili kişi başvurusu'),
  PrivacyAssessment: tx('Etki değerlendirmesi'),
  PrivacyNotice: tx('Aydınlatma metni'),
  Consent: tx('Rıza'),
  FieldPolicy: tx('Alan yetkisi'),
  RetentionPolicy: tx('Saklama kuralı'),
  DestructionLog: tx('İmha tutanağı'),
  AnalysisObjection: tx('Analiz itirazı'),
  AuditChain: tx('Denetim zinciri'),
  CalendarEventLink: tx('Takvim etkinliği'),
  CalendarConnection: tx('Takvim bağlantısı'),
  CategoryPreference: tx('Kategori tercihi'),
  EmployeeProfile: tx('Çalışan profili'),
  Employee: tx('Çalışan'),
  EmployeeList: tx('Çalışan listesi'),
  Department: tx('Departman'),
  Team: tx('Ekip'),
  Tenant: tx('Şirket'),
  DirectoryUser: tx('Dizin kullanıcısı'),
  DirectorySettings: tx('Dizin ayarları'),
  ProviderConfig: tx('Sağlayıcı ayarı'),
  PushSubscription: tx('Anlık bildirim aboneliği'),
  OAuthState: tx('Oturum bağlantı durumu'),
  ApiKey: tx('API anahtarı'),
  ScimToken: tx('SCIM belirteci'),
  Webhook: tx('Webhook'),
  CustomDomain: tx('Özel alan adı'),
  CustomField: tx('Özel alan'),
  DocumentSignature: tx('Belge imzası'),
  DocumentRequest: tx('Belge talebi'),
  DocTemplate: tx('Belge şablonu'),
  Document: tx('Doküman'),
  Asset: tx('Zimmet'),
  AssetAssignment: tx('Zimmet ataması'),
  OnboardingPlan: tx('İşe alıştırma planı'),
  OnboardingTask: tx('İşe alıştırma görevi'),
  TaskTemplate: tx('Görev şablonu'),
  TaskTemplateItem: tx('Görev şablonu maddesi'),
  Survey: tx('Anket'),
  Kudos: tx('Takdir'),
  OneOnOne: tx('1:1 görüşme'),
  Meeting: tx('Toplantı'),
  Desk: tx('Masa'),
  DeskBooking: tx('Masa rezervasyonu'),
  Presence: tx('Ofis/uzaktan durumu'),
  Course: tx('Eğitim'),
  CourseModule: tx('Eğitim modülü'),
  CourseCompetency: tx('Eğitim yetkinliği'),
  Enrollment: tx('Eğitim kaydı'),
  ModuleProgress: tx('Modül ilerlemesi'),
  QuizQuestion: tx('Sınav sorusu'),
  QuizAttempt: tx('Sınav denemesi'),
  LearningResult: tx('Eğitim sonucu'),
  Certification: tx('Sertifika'),
  Assignment: tx('Eğitim ataması'),
  Competency: tx('Yetkinlik'),
  CompetencyTeam: tx('Ekip yetkinliği'),
  CompetencyGap: tx('Yetkinlik açığı'),
  CompetencyAssessment: tx('Yetkinlik değerlendirmesi'),
  RoleProfileEntry: tx('Rol profili'),
  NineBox: tx('9 kutu'),
  PotentialRating: tx('Potansiyel puanı'),
  PerformanceSnapshot: tx('Performans özeti'),
  Review: tx('Performans değerlendirmesi'),
  ReviewCycle: tx('Değerlendirme dönemi'),
  CycleTemplate: tx('Dönem şablonu'),
  AttritionRisk: tx('Ayrılma riski'),
  DisciplinaryCase: tx('Disiplin dosyası'),
  EthicsReport: tx('Etik bildirimi'),
  EthicsCommittee: tx('Etik kurul'),
  HrCase: tx('İK talebi'),
  KbArticle: tx('Bilgi bankası makalesi'),
  ExpenseClaim: tx('Masraf talebi'),
  ExpenseItem: tx('Masraf kalemi'),
  TravelRequest: tx('Seyahat talebi'),
  Report: tx('Rapor'),
  MetricDefinition: tx('Metrik tanımı'),
}

export const auditActionLabel = (a: string) => auditActionLabels[a] ?? a
export const auditEntityLabel = (e: string) => auditEntityLabels[e] ?? e
